dist: trusty
language: php

sudo: required

 # Downloaded browsers will be cached in selenium-assistant by
 # web-push-testing-service. Caching will speed up build time.
cache:
  directories:
    - ~/.selenium-assistant

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true
    include:
        - php: 7.1
        - php: 7.2
        - php: nightly

env:
  - TRAVIS_NODE_VERSION="stable"

before_install:
  - nvm install node

install:
  - npm install github:GoogleChromeLabs/web-push-testing-service -g

before_script:
  - composer install --prefer-source -n
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
  - sleep 3 # give xvfb some time to start

script:
  - web-push-testing-service start example -p 9012
  - ./vendor/bin/phpunit
  - web-push-testing-service stop example

after_script:
  - ./vendor/bin/phpstan analyse --level max src
